#!/usr/bin/env bash
# Start a wordpress (multi)site from a git repo and autoupgrade it.

# We need a path
test $# -eq 0 &&
echo "I need the path to clone wordpress into" &&
exit

# Remove trailing slash
site="$(echo "$1" | sed "s,/$,,")"

# Clone or fetch?
if test -d "${site}/.git" ; then
  pushd "${site}"
  git fetch origin
else
  git clone https://github.com/WordPress/WordPress "${site}"
  pushd "${site}"
fi

# Restore write permissions
# Allow everything to user, read to group and nothing to everyone else
find -type d -exec chmod 750 {} \;
find -type f -exec chmod 640 {} \;

# Checkout the latest released version
git checkout --force "$(git tag | sort --version-sort | tail --lines=1)"

# Remove write permissions, but keep them on uploads
find -type d | grep --invert-match "uploads/" | xargs chmod 550
find -type f | grep --invert-match "uploads/" | xargs chmod 440

# TODO
# * upgrade plugins (how?)
# * upgrade themes (how?)
